export default function WeeklyDigest({ digest }) {
  return (
    <div>
      <h3 className="text-sm font-semibold text-white mb-1">Weekly AI Analysis</h3>
      <p className="text-xs text-zinc-500 mb-4">
        Auto-generated by Claude · {digest.week_display}
      </p>

      <div className="space-y-3">
        {digest.insights.map((ins, i) => (
          <div key={i} className="border border-zinc-800 rounded-xl p-4">
            <div className="flex justify-between items-center mb-2">
              <span className="font-semibold text-sm text-white">{ins.title}</span>
              <span className={`text-xs font-semibold tabular-nums ${
                ins.direction === 'up' ? 'text-emerald-400' :
                ins.direction === 'down' ? 'text-orange-400' :
                'text-zinc-400'
              }`}>
                {ins.direction === 'up' ? '▲' : ins.direction === 'down' ? '▼' : '●'} {ins.delta}
              </span>
            </div>
            <p className="text-xs text-zinc-400 leading-relaxed">{ins.body}</p>
          </div>
        ))}
      </div>

      <div className="mt-4 p-3 bg-zinc-900 rounded-lg text-xs text-zinc-500 text-center">
        Past analyses:{' '}
        {['W11', 'W10', 'W09', '2025 Q4 Report'].map((label, i) => (
          <span key={label}>
            {i > 0 && ' · '}
            <span className="text-blue-400 cursor-pointer hover:underline">{label}</span>
          </span>
        ))}
      </div>
    </div>
  )
}
