#!/usr/bin/env python3
"""
Push VLA-Tracker leaderboard data to HuggingFace as a dataset.

Usage:
  # First time: login with `huggingface-cli login`
  python scripts/push_to_hf.py

  # Or set HF_TOKEN environment variable
  HF_TOKEN=hf_xxx python scripts/push_to_hf.py

  # Dry run (just generate files, don't push)
  python scripts/push_to_hf.py --dry-run

The dataset will be available at:
  https://huggingface.co/datasets/{HF_USER}/vla-tracker-leaderboard
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEADERBOARD = ROOT / "data" / "leaderboard.json"
AI_REVIEWS_DIR = ROOT / "data" / "ai_reviews"

# Default HF repo (override with --repo)
DEFAULT_REPO = "vla-tracker-leaderboard"


def build_dataset_card(data: dict) -> str:
    """Generate a HuggingFace dataset card (README.md)."""
    n_models = data["num_models"]
    libero_top = [m for m in data["models"] if m.get("libero_avg")][:5]
    top_str = "\n".join(
        f"| {i+1} | {m['name']} | {m['libero_avg']} | {m['organization']} |"
        for i, m in enumerate(libero_top)
    )

    return f"""---
license: mit
task_categories:
  - robotics
tags:
  - vla
  - vision-language-action
  - robotics
  - benchmark
  - leaderboard
size_categories:
  - n<1K
pretty_name: VLA-Tracker Leaderboard
---

# VLA-Tracker Leaderboard Dataset

Comprehensive benchmark tracking for **{n_models} Vision-Language-Action (VLA) models** across 8 benchmarks.

## What's included

- **leaderboard.json** — Full model data with architecture, benchmark scores, AI reviews
- **models/** — Individual model YAML files
- **ai_reviews/** — 70 AI-generated paper reviews (26 PDF-verified)

## Current LIBERO Top 5

| Rank | Model | Avg | Organization |
|------|-------|-----|-------------|
{top_str}

## Benchmarks

LIBERO, CALVIN, SimplerEnv, RoboTwin v1/v2, RLBench, RoboCasa, Meta-World

## Usage

```python
from datasets import load_dataset

ds = load_dataset("{DEFAULT_REPO}")
# Or directly:
import json, urllib.request
data = json.loads(urllib.request.urlopen(
    "https://huggingface.co/datasets/{DEFAULT_REPO}/resolve/main/leaderboard.json"
).read())
```

## Links

- [Interactive Dashboard](https://hyeongjinkim.github.io/Vla-tracker-/)
- [GitHub Repository](https://github.com/HyeongjinKim/Vla-tracker-)
- [llms.txt](https://hyeongjinkim.github.io/Vla-tracker-/llms.txt)

## License

MIT — Data sourced from published papers. AI reviews generated by Claude.

## Citation

```bibtex
@misc{{vla-tracker-2026,
  title={{VLA-Tracker: Benchmark Dashboard for Vision-Language-Action Models}},
  author={{Hyeongjin Kim}},
  year={{2026}},
  url={{https://github.com/HyeongjinKim/Vla-tracker-}}
}}
```
"""


def main():
    parser = argparse.ArgumentParser(description="Push VLA-Tracker to HuggingFace")
    parser.add_argument("--repo", default=DEFAULT_REPO, help="HF dataset repo name")
    parser.add_argument("--dry-run", action="store_true", help="Generate files but don't push")
    args = parser.parse_args()

    # Load data
    print("Loading leaderboard...")
    with open(LEADERBOARD) as f:
        data = json.load(f)
    print(f"  {data['num_models']} models loaded")

    if args.dry_run:
        print("\n[DRY RUN] Would push to HuggingFace:")
        print(f"  Repo: {args.repo}")
        print(f"  Files: leaderboard.json, README.md, {len(list(AI_REVIEWS_DIR.glob('*.md')))} reviews")
        return 0

    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        print("Error: huggingface_hub not installed. Run: pip install huggingface_hub")
        return 1

    api = HfApi()

    # Check auth
    try:
        user = api.whoami()
        username = user["name"]
        repo_id = f"{username}/{args.repo}"
        print(f"  Authenticated as: {username}")
    except Exception:
        print("Error: Not authenticated. Run: huggingface-cli login")
        print("  Or set HF_TOKEN environment variable")
        return 1

    # Create or update repo
    print(f"\nPushing to: {repo_id}")
    try:
        create_repo(repo_id, repo_type="dataset", exist_ok=True)
    except Exception as e:
        print(f"  Repo creation: {e}")

    # Upload leaderboard.json
    print("  Uploading leaderboard.json...")
    api.upload_file(
        path_or_fileobj=str(LEADERBOARD),
        path_in_repo="leaderboard.json",
        repo_id=repo_id,
        repo_type="dataset",
    )

    # Upload dataset card
    card = build_dataset_card(data)
    import tempfile
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(card)
        card_path = f.name
    api.upload_file(
        path_or_fileobj=card_path,
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
    )

    # Upload AI reviews
    reviews = list(AI_REVIEWS_DIR.glob("*.md"))
    if reviews:
        print(f"  Uploading {len(reviews)} AI reviews...")
        api.upload_folder(
            folder_path=str(AI_REVIEWS_DIR),
            path_in_repo="ai_reviews",
            repo_id=repo_id,
            repo_type="dataset",
        )

    # Upload model YAMLs
    models_dir = ROOT / "data" / "models"
    yamls = list(models_dir.glob("*.yaml"))
    if yamls:
        print(f"  Uploading {len(yamls)} model YAMLs...")
        api.upload_folder(
            folder_path=str(models_dir),
            path_in_repo="models",
            repo_id=repo_id,
            repo_type="dataset",
        )

    print(f"\nDone! Dataset available at: https://huggingface.co/datasets/{repo_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
